global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nestjs'
    static_configs:
      - targets: ['app:3030']  # 使用 Docker 服务名称
    metrics_path: '/metrics'   # NestJS 应用的指标路径

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']  # RabbitMQ 管理界面端口
    metrics_path: '/api/metrics'      # RabbitMQ 指标路径

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 